# Generated by Django 4.1 on 2022-09-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_postmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default_post.jpg', upload_to='post_images'),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='image',
            field=models.ImageField(default='default_post.jpg', upload_to='post_images'),
        ),
    ]
