# Generated by Django 4.1 on 2022-09-04 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('short_desc', models.CharField(max_length=300, null=True)),
                ('content', models.TextField(null=True)),
                ('image', models.ImageField(default='default_post.jpg', upload_to='post_images')),
                ('date_posted', models.DateTimeField(auto_now_add=True, null=True)),
                ('post_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_posted',),
            },
        ),
        migrations.CreateModel(
            name='project_donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(null=True)),
                ('p_method', models.CharField(choices=[('Bkash', 'Bkash'), ('Nagad', 'Nagad'), ('Rocket', 'Rocket')], max_length=10, null=True)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('txid', models.CharField(max_length=30, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Received', 'Received'), ('Declined', 'Declined')], default='Pending', max_length=15, null=True)),
                ('date_donated', models.DateTimeField(auto_now_add=True, null=True)),
                ('donor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
            ],
            options={
                'ordering': ('-date_donated',),
            },
        ),
    ]
