# Generated by Django 4.1 on 2022-09-04 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_project_donation_projectdonation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='default_post.jpg', upload_to='project_images'),
        ),
    ]
