# Generated by Django 4.1 on 2022-09-05 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_projectdonation_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdonation',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project'),
        ),
    ]
