# Generated by Django 4.0.6 on 2022-08-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_money_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money_donation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Received', 'Received'), ('Declined', 'Declined')], default='Pending', max_length=15, null=True),
        ),
    ]
