# Generated by Django 4.0.6 on 2022-08-20 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='money_donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(null=True)),
                ('p_method', models.CharField(choices=[('Bkash', 'Bkash'), ('Nagad', 'Nagad'), ('Rocket', 'Rocket')], max_length=10, null=True)),
                ('txid', models.CharField(max_length=30, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Received', 'Received'), ('Declined', 'Declined')], default='Pending', max_length=15, null=True)),
                ('date_donated', models.DateTimeField(auto_now_add=True, null=True)),
                ('donor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='food_donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Picked', 'Picked'), ('About to Be Picked', 'About to Be Picked'), ('Received', 'Received'), ('Declined', 'Declined')], default='Pending', max_length=20, null=True)),
                ('date_donated', models.DateTimeField(auto_now_add=True, null=True)),
                ('d_user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='cloth_donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.TextField(null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Picked', 'Picked'), ('About to Be Picked', 'About to Be Picked'), ('Received', 'Received'), ('Declined', 'Declined')], default='Pending', max_length=20, null=True)),
                ('date_donated', models.DateTimeField(auto_now_add=True, null=True)),
                ('d_user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
