# Generated by Django 4.0.6 on 2022-08-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloth_donation',
            old_name='items',
            new_name='items_description',
        ),
        migrations.AddField(
            model_name='cloth_donation',
            name='total_items',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='food_donation',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
