# Generated by Django 4.1 on 2022-09-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_rename_items_cloth_donation_items_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_donation',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
