# Generated by Django 4.1 on 2022-09-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_alter_food_donation_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cloth_donation',
            options={'ordering': ('-date_donated',)},
        ),
        migrations.AlterModelOptions(
            name='food_donation',
            options={'ordering': ('-date_donated',)},
        ),
        migrations.AlterModelOptions(
            name='money_donation',
            options={'ordering': ('-date_donated',)},
        ),
        migrations.AlterField(
            model_name='cloth_donation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Picked', 'Picked'), ('About to Be Picked', 'About to Be Picked'), ('Received', 'Received'), ('Delivered', 'Delivered'), ('Declined', 'Declined')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='food_donation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Picked', 'Picked'), ('About to Be Picked', 'About to Be Picked'), ('Received', 'Received'), ('Delivered', 'Delivered'), ('Declined', 'Declined')], default='Pending', max_length=20, null=True),
        ),
    ]
