# Generated by Django 4.1 on 2022-09-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_alter_cloth_donation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth_donation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Picked', 'Picked'), ('About to Be Picked', 'About to Be Picked'), ('Received', 'Received'), ('Delivered', 'Delivered'), ('Declined', 'Declined')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='food_donation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Picked', 'Picked'), ('About to Be Picked', 'About to Be Picked'), ('Received', 'Received'), ('Delivered', 'Delivered'), ('Declined', 'Declined')], default='Pending', max_length=20, null=True),
        ),
    ]
