# Generated by Django 4.1 on 2022-09-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_alter_cloth_donation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='money_donation',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
