# Generated by Django 4.1 on 2022-09-05 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_clothinventory_foodinventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothinventory',
            old_name='punjabi',
            new_name='panjabi',
        ),
    ]
